import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { runWithFailover } from "@/lib/failover";
import { authApiKey } from "@/lib/auth";
import {
  reorderProvidersOpenSourceFirst,
  type ChatMessage,
} from "@/lib/providers";

/**
 * POST /api/v1/custom/chat/completions
 *
 * OpenAI-compatible chat completions endpoint that routes ONLY through the
 * provider chain configured on the caller's Custom API. This is the
 * "customized API" the user built — a small, fast, reliable chain of
 * providers (open-source first, paid fallback) instead of the full 30+
 * provider failover.
 *
 * Authentication:
 *   Bearer marq_live_... — the API key generated by POST /api/custom-apis.
 *   The key must have the "custom" scope and be linked to a CustomApiConfig.
 *
 * Request body (OpenAI-compatible):
 *   messages: [{ role: "system"|"user"|"assistant", content: string }, ...]
 *   model?: string              — ignored, failover picks per-provider
 *   stream?: boolean            — not supported yet, returns 400 if true
 *   session_id?: string         — optional Marq session to write into
 *
 * Response (OpenAI shape) with a `marq` extension:
 *   {
 *     id, object: "chat.completion", created, model,
 *     choices: [{ index: 0, message: {...}, finish_reason: "stop" }],
 *     usage: { prompt_tokens, completion_tokens, total_tokens },
 *     marq: {
 *       customApi: { id, name },
 *       provider: { id, name, displayName },
 *       originalProvider: ... | null,
 *       failedOver, fallback, attempts, latencyMs, sessionId
 *     }
 *   }
 */
export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 30;

export async function POST(req: NextRequest) {
  // ── Authenticate with the custom-scoped API key ──
  const auth = await authApiKey(req, "custom");
  if (auth instanceof NextResponse) return auth;

  const body = await req.json().catch(() => ({}));
  const { messages, session_id, stream } = body ?? {};

  if (stream) {
    return NextResponse.json(
      { error: "Streaming not yet supported by the custom API" },
      { status: 400 }
    );
  }
  if (!Array.isArray(messages) || messages.length === 0) {
    return NextResponse.json(
      { error: "messages must be a non-empty array" },
      { status: 400 }
    );
  }

  // Map to internal ChatMessage type.
  const mapped: ChatMessage[] = [];
  for (const m of messages) {
    if (
      m?.role &&
      m?.content != null &&
      ["system", "user", "assistant"].includes(m.role)
    ) {
      mapped.push({ role: m.role, content: String(m.content) });
    }
  }
  if (mapped.length === 0) {
    return NextResponse.json(
      { error: "No valid messages found" },
      { status: 400 }
    );
  }

  // ── Resolve the CustomApiConfig linked to this API key ──
  const apiKey = await db.apiKey.findUnique({
    where: { id: auth.apiKeyId },
    include: { customApis: true },
  });

  if (!apiKey || apiKey.revokedAt) {
    return NextResponse.json(
      { error: "API key revoked or not found" },
      { status: 401 }
    );
  }

  if (apiKey.customApis.length === 0) {
    return NextResponse.json(
      {
        error:
          "This API key is not linked to a Custom API. Build one at /api/custom-apis first.",
      },
      { status: 403 }
    );
  }

  // Use the most recently created config linked to this key.
  const config = apiKey.customApis.sort(
    (a, b) => b.createdAt.getTime() - a.createdAt.getTime()
  )[0];

  // ── Build the provider chain from the config ──
  let providerIds: string[] = [];
  try {
    providerIds = JSON.parse(config.providerIds);
  } catch {
    return NextResponse.json(
      { error: "Custom API config has invalid providerIds" },
      { status: 500 }
    );
  }

  if (providerIds.length === 0) {
    return NextResponse.json(
      { error: "Custom API config has no providers" },
      { status: 500 }
    );
  }

  // Load providers in the exact order specified by the config.
  const providers = await db.provider.findMany({
    where: { id: { in: providerIds }, active: true },
  });

  if (providers.length === 0) {
    return NextResponse.json(
      { error: "No active providers found in the custom chain" },
      { status: 503 }
    );
  }

  // Sort by the config's order, then optionally apply open-source-first.
  const idToOrder = new Map(providerIds.map((id, i) => [id, i]));
  providers.sort((a, b) => {
    const ao = idToOrder.get(a.id) ?? 999;
    const bo = idToOrder.get(b.id) ?? 999;
    return ao - bo;
  });

  let finalProviders = providers;
  if (config.openSourceFirst) {
    // Apply open-source-first on top of the user's order. This keeps
    // the user's explicit primary at the front but reorders the rest.
    finalProviders = reorderProvidersOpenSourceFirst(providers);
    // Re-pin the user's original primary (index 0 of providerIds) to front.
    const userPrimary = providers.find((p) => p.id === providerIds[0]);
    if (userPrimary) {
      finalProviders = [
        userPrimary,
        ...finalProviders.filter((p) => p.id !== userPrimary.id),
      ];
    }
  }

  // ── Resolve / create a Marq session ──
  let session = session_id
    ? await db.chatSession.findUnique({ where: { id: session_id } })
    : null;
  if (session && session.orgId && session.orgId !== auth.orgId) {
    return NextResponse.json(
      { error: "session_id belongs to a different org" },
      { status: 403 }
    );
  }
  if (!session) {
    const title = (mapped[mapped.length - 1]?.content ?? "Custom API call").slice(0, 50);
    session = await db.chatSession.create({
      data: { orgId: auth.orgId, title },
    });
  }

  // Persist user messages for audit.
  for (const m of mapped) {
    if (m.role !== "assistant") {
      await db.message.create({
        data: { sessionId: session.id, role: m.role, content: m.content },
      });
    }
  }

  // ── Run the failover through the custom chain ──
  try {
    const outcome = await runWithFailover({
      providers: finalProviders,
      messages: mapped,
      sessionId: session.id,
      timeoutMs: config.timeoutMs,
    });

    const finalProvider = finalProviders.find(
      (p) => p.id === outcome.finalProviderId
    )!;

    // Update lastUsedAt on the API key.
    await db.apiKey.update({
      where: { id: auth.apiKeyId },
      data: { lastUsedAt: new Date() },
    }).catch(() => {});

    const assistantMessage = await db.message.create({
      data: {
        sessionId: session.id,
        role: "assistant",
        content: outcome.result.content,
        providerId: finalProvider.id,
        model: outcome.result.model,
        latencyMs: outcome.result.latencyMs,
        tokensUsed: outcome.result.tokensUsed ?? null,
        failedOver: outcome.failedOver,
        originalProviderId: outcome.originalProviderId,
      },
    });

    return NextResponse.json({
      id: `chatcmpl-${assistantMessage.id}`,
      object: "chat.completion",
      created: Math.floor(assistantMessage.createdAt.getTime() / 1000),
      model: outcome.result.model,
      choices: [
        {
          index: 0,
          message: { role: "assistant", content: outcome.result.content },
          finish_reason: "stop",
        },
      ],
      usage: {
        prompt_tokens: Math.ceil(
          mapped.map((m) => m.content).join("").length / 4
        ),
        completion_tokens:
          outcome.result.tokensUsed ??
          Math.ceil(outcome.result.content.length / 4),
        total_tokens:
          (outcome.result.tokensUsed ??
            Math.ceil(outcome.result.content.length / 4)) +
          Math.ceil(mapped.map((m) => m.content).join("").length / 4),
      },
      marq: {
        customApi: { id: config.id, name: config.name },
        provider: {
          id: finalProvider.id,
          name: finalProvider.name,
          displayName: finalProvider.displayName,
        },
        originalProvider: outcome.failedOver
          ? (() => {
              const o = finalProviders.find(
                (p) => p.id === outcome.originalProviderId
              );
              return o
                ? { id: o.id, name: o.name, displayName: o.displayName }
                : null;
            })()
          : null,
        failedOver: outcome.failedOver,
        fallback: outcome.fallback ?? false,
        attempts: outcome.attempts,
        latencyMs: outcome.result.latencyMs,
        sessionId: session.id,
      },
    });
  } catch (err) {
    return NextResponse.json(
      {
        error: {
          message: err instanceof Error ? err.message : "All providers in the custom chain failed",
          type: "upstream_error",
        },
      },
      { status: 502 }
    );
  }
}
