#!/usr/bin/env python3
"""
Append missing AI tools from infrabase.ai/alternatives/ollama to provider-benefits.ts.

Adds 27 new ProviderBenefit entries with rich metadata following the existing schema.
Inserts them just before the `KIND_META` definition.
"""

import re
from pathlib import Path

PATH = Path("/home/z/my-project/src/lib/provider-benefits.ts")
content = PATH.read_text()

# Each entry follows the schema in the file.
# icon must be in ICON_MAP in ai-directory-panel.tsx
NEW_ENTRIES = [
    # ── Direct Ollama alternatives ──────────────────────────────────
    {
        "name": "llamacpp",
        "displayName": "llama.cpp",
        "tagline": "Pure C/C++ LLM inference engine — the engine Ollama wraps, with fine control over quantization and sampling.",
        "icon": "Code2",
        "color": "#4a5568",
        "category": "local",
        "kind": "framework",
        "popularity": "very-high",
        "bestFor": [
            "Running GGUF models on CPU-only laptops and edge devices",
            "Fine-grained control over quantization (Q4_K_M, Q5_K_S, Q8_0)",
            "Embedded inference via the C API — no Python runtime required",
            "Research and benchmarking on new quantization formats",
            "Building custom inference servers with the bundled HTTP server",
        ],
        "capabilities": [
            "Convert and quantize Hugging Face models to GGUF",
            "Serve models locally with an OpenAI-compatible HTTP API",
            "Run on macOS Metal, CUDA, ROCm, Vulkan, and SYCL backends",
            "Tune sampling params (temperature, top-k, top-p, repetition penalty)",
            "Use as the inference core inside Ollama, LM Studio, Jan, and others",
        ],
        "whenToUse": [
            "You want maximum control over the inference pipeline",
            "You're targeting CPU-only or low-power hardware",
            "You need a custom quantization or sampling recipe",
            "You're benchmarking inference kernels",
        ],
        "limitations": [
            "No built-in model discovery or GUI — CLI and HTTP only",
            "Manual model conversion required for non-GGUF checkpoints",
            "Not optimized for high-throughput multi-tenant serving (use vLLM instead)",
        ],
        "samplePrompts": [
            "Quantize mistral-7b-instruct to Q4_K_M with llama-quantize",
            "Run a GGUF model with 4-bit quantization on CPU",
            "Start the llama.cpp server with --n-gpu-layers 35 for partial GPU offload",
        ],
        "setupNotes": "Build from source with `make` (CPU) or `make LLAMA_CUDA=1` (NVIDIA). Download a GGUF model from Hugging Face, then run `./llama-server -m model.gguf --port 8080 --n-gpu-layers 35`. Marq can connect to the resulting OpenAI-compatible endpoint via a generic OpenAI-compatible provider.",
        "pricingTier": "Free / open source (MIT)",
        "docsUrl": "https://github.com/ggerganov/llama.cpp",
        "availableModels": ["(any GGUF model)", "Llama 3", "Mistral 7B", "Phi-3", "Qwen2.5"],
        "availableAgents": ["local-researcher", "summarizer", "code-reviewer"],
        "advantages": [
            "Smallest, fastest pure-C inference core — runs anywhere a C compiler does",
            "Aggressive quantization (2-8 bit) with negligible quality loss on modern formats",
            "Multi-backend: CPU, CUDA, Metal, ROCm, Vulkan, SYCL",
            "Reference implementation for the GGUF format",
            "Bundled OpenAI-compatible HTTP server",
        ],
        "businessAdvantages": [
            "Zero licensing cost — MIT licensed",
            "No Python or Docker required — minimal attack surface",
            "Same engine Ollama, LM Studio, and Jan depend on",
            "Easy to embed in edge devices and appliances",
        ],
        "apiIntegrationDetails": "GET http://localhost:8080/v1/models | POST http://localhost:8080/v1/chat/completions { model, messages } — OpenAI-compatible.",
    },
    {
        "name": "lmstudio",
        "displayName": "LM Studio",
        "tagline": "Polished desktop GUI for discovering, downloading, and running local LLMs with a built-in OpenAI server.",
        "icon": "MonitorSmartphone",
        "color": "#7c3aed",
        "category": "local",
        "kind": "framework",
        "popularity": "very-high",
        "bestFor": [
            "Non-developers who want a ChatGPT-like local LLM experience",
            "Browsing and trying models from Hugging Face without a CLI",
            "Quick local prototyping against an OpenAI-compatible endpoint",
            "Running vision and embedding models on consumer GPUs",
        ],
        "capabilities": [
            "Search Hugging Face and download GGUF models with one click",
            "Chat with local models in a polished desktop UI",
            "Expose a local OpenAI-compatible API server on :1234",
            "Load multiple models simultaneously (RAM permitting)",
            "Hardware auto-detection — CPU, Apple Silicon, NVIDIA, AMD",
        ],
        "whenToUse": [
            "You want point-and-click model management",
            "You're on macOS or Windows and don't want to touch a terminal",
            "You need to expose a local API for Marq to route to",
        ],
        "limitations": [
            "Closed source (free for personal and work use, no redistribution)",
            "Desktop-only — no headless Linux server build",
            "Not designed for high-throughput multi-user serving",
        ],
        "samplePrompts": [
            "Download and run Qwen2.5-7B-Instruct in LM Studio",
            "Start the LM Studio local server on port 1234",
            "Compare Llama 3.1 vs Mistral side-by-side in LM Studio",
        ],
        "setupNotes": "Install from lmstudio.ai, browse the model directory, download a model, switch to the 'Local Server' tab and click Start. Point Marq at http://localhost:1234/v1 as a generic OpenAI-compatible provider.",
        "pricingTier": "Free for personal and work use",
        "docsUrl": "https://lmstudio.ai/docs",
        "availableModels": ["(any GGUF on Hugging Face)", "Llama 3.1", "Mistral", "Qwen2.5", "Phi-3"],
        "availableAgents": ["local-researcher", "summarizer", "code-reviewer"],
        "advantages": [
            "Best-in-class desktop GUI with model browser and side-by-side chat",
            "One-click OpenAI-compatible local server",
            "Auto-detects Apple Metal, NVIDIA CUDA, and AMD ROCm",
            "Built-in model card and chat metadata",
            "Multi-model parallel loading",
        ],
        "businessAdvantages": [
            "Free for commercial workplace use",
            "Eliminates cloud egress costs for local inference",
            "Onboards non-engineers to local LLMs without a CLI",
            "Works offline once models are downloaded",
        ],
        "apiIntegrationDetails": "POST http://localhost:1234/v1/chat/completions { model, messages } — drop-in OpenAI replacement. No auth header required by default.",
    },
    {
        "name": "jan",
        "displayName": "Jan",
        "tagline": "Open-source (Apache-2.0) desktop app for offline LLMs — ChatGPT-style UI with built-in model management.",
        "icon": "Coffee",
        "color": "#0ea5e9",
        "category": "local",
        "kind": "framework",
        "popularity": "high",
        "bestFor": [
            "Privacy-first users wanting a fully open-source local LLM app",
            "Cross-platform desktop use (macOS, Windows, Linux)",
            "Optional remote API connections alongside local models",
            "Self-hostable assistant UI for non-technical teams",
        ],
        "capabilities": [
            "Download and run GGUF models locally with a ChatGPT-like UI",
            "Built-in chat history and thread management",
            "Connect to remote OpenAI-compatible endpoints (Marq, OpenAI, Ollama)",
            "Cortex.cpp backend — fast inference with CUDA/Metal/CPU/Vulkan",
            "Plugin system for tools and extensions",
        ],
        "whenToUse": [
            "You need a fully open-source alternative to LM Studio",
            "You want to mix local and remote providers in one UI",
            "Compliance requires Apache-2.0 licensed tooling",
        ],
        "limitations": [
            "Smaller plugin ecosystem than LM Studio or Ollama",
            "Mobile clients still in development",
            "Less mature model marketplace UX",
        ],
        "samplePrompts": [
            "Install Jan and download Llama 3.1 8B Instruct",
            "Connect Jan to Marq's OpenAI-compatible /api/v1 endpoint",
            "Use Jan's API server for local inference",
        ],
        "setupNotes": "Download from jan.ai, browse models, download, chat. To expose an OpenAI-compatible API, enable the local server in Settings → API. Point Marq at http://localhost:1337/v1.",
        "pricingTier": "Free / open source (Apache-2.0)",
        "docsUrl": "https://jan.ai/docs",
        "availableModels": ["(any GGUF model)", "Llama 3.1", "Qwen2.5", "Mistral", "Phi-3"],
        "availableAgents": ["local-researcher", "summarizer"],
        "advantages": [
            "100% open source (Apache-2.0) — auditable and self-hostable",
            "Cortex.cpp backend with broad hardware support",
            "Unified UI for local + remote providers",
            "Built-in chat history with export",
            "Plugin architecture for extensibility",
        ],
        "businessAdvantages": [
            "Apache-2.0 license is enterprise-friendly",
            "Reduces dependence on closed-source desktop apps",
            "Works fully offline after model download",
            "Active community and roadmap",
        ],
        "apiIntegrationDetails": "POST http://localhost:1337/v1/chat/completions { model, messages } — OpenAI-compatible. API key configurable in Settings → API Keys.",
    },
    {
        "name": "gpt4all",
        "displayName": "GPT4All",
        "tagline": "Desktop app + Python SDK from Nomic AI for running open-source LLMs locally — includes LocalDocs for RAG.",
        "icon": "Laptop",
        "color": "#10b981",
        "category": "local",
        "kind": "framework",
        "popularity": "high",
        "bestFor": [
            "Running LLMs on laptops without a GPU",
            "RAG over local files via the LocalDocs feature",
            "Embedding generation with Nomic Embed",
            "Free commercial use (MIT license)",
        ],
        "capabilities": [
            "Chat with quantized models on CPU or GPU",
            "LocalDocs — point at a folder, get RAG over your files",
            "Python SDK for programmatic inference",
            "Built-in embedding model (Nomic Embed)",
            "Cross-platform desktop chat app",
        ],
        "whenToUse": [
            "You need to chat with your local documents privately",
            "Your hardware is CPU-only or low VRAM",
            "You want an MIT-licensed embeddable SDK",
        ],
        "limitations": [
            "Smaller model catalog than LM Studio or Ollama",
            "Slower than llama.cpp direct on bare metal",
            "LocalDocs RAG is basic — no advanced chunking or reranking",
        ],
        "samplePrompts": [
            "Install GPT4All and enable LocalDocs on my PDFs folder",
            "Use the GPT4All Python SDK to embed 1000 sentences",
            "Compare GPT4All vs Ollama for CPU inference",
        ],
        "setupNotes": "Download from gpt4all.io, install, browse models, download. Enable LocalDocs in Settings and add a folder. For SDK use: `pip install gpt4all` then `from gpt4all import GPT4All; model = GPT4All('orca-mini-3b.gguf')`.",
        "pricingTier": "Free / open source (MIT)",
        "docsUrl": "https://docs.gpt4all.io",
        "availableModels": ["orca-mini", "Llama 3", "Mistral", "Phi-3", "Qwen2", "nomic-embed-text"],
        "availableAgents": ["local-researcher", "summarizer", "rag-docs"],
        "advantages": [
            "MIT licensed — free for any commercial use",
            "LocalDocs feature — folder → RAG with no setup",
            "Best CPU inference on the desktop",
            "Nomic Embed built in for embeddings + clustering",
            "Python SDK for programmatic access",
        ],
        "businessAdvantages": [
            "Zero licensing cost — MIT",
            "On-prem RAG over confidential documents",
            "Embeddable in Python pipelines",
            "Backed by Nomic AI — active development",
        ],
        "apiIntegrationDetails": "Desktop app exposes no HTTP server by default. Use the Python SDK: `from gpt4all import GPT4All; model = GPT4All('model.gguf'); print(model.generate('prompt'))`.",
    },
    {
        "name": "localai",
        "displayName": "LocalAI",
        "tagline": "Open-source, self-hosted OpenAI-compatible API for running models on your own hardware — drop-in replacement for the OpenAI API.",
        "icon": "Server",
        "color": "#dc2626",
        "category": "local",
        "kind": "framework",
        "popularity": "high",
        "bestFor": [
            "Self-hosting an OpenAI-compatible API on your own GPUs",
            "Multi-tenant local inference for a team",
            "Running text, image, and audio models behind one API",
            "Replacing OpenAI without changing client code",
        ],
        "capabilities": [
            "OpenAI-compatible /v1/chat/completions, /v1/completions, /v1/embeddings",
            "Text-to-image via Stable Diffusion",
            "Audio transcription via Whisper",
            "Backend-agnostic: llama.cpp, vLLM, diffusers, whisper.cpp",
            "Docker-first deployment with model galleries",
        ],
        "whenToUse": [
            "You want to self-host an OpenAI-compatible API server",
            "You need text + image + audio behind one endpoint",
            "Multi-tenant — multiple teams hitting one GPU box",
        ],
        "limitations": [
            "Requires Docker and GPU for production throughput",
            "Model gallery is smaller than Hugging Face Hub",
            "Configuration overhead vs Ollama for laptop use",
        ],
        "samplePrompts": [
            "Deploy LocalAI in Docker with the llama.cpp backend",
            "Use LocalAI's /v1/embeddings endpoint with Marq",
            "Generate an image with LocalAI's Stable Diffusion backend",
        ],
        "setupNotes": "Docker: `docker run -p 8080:8080 -v models:/models quay.io/go-skynet/local-ai:latest`. Then `curl http://localhost:8080/v1/chat/completions -d '{\"model\":\"llama-3\",\"messages\":[...]}'`. Marq can use this as a generic OpenAI-compatible provider.",
        "pricingTier": "Free / open source (MIT)",
        "docsUrl": "https://localai.io",
        "availableModels": ["(any GGUF, diffusers, or whisper model)", "Llama 3", "Mistral", "Stable Diffusion", "Whisper"],
        "availableAgents": ["local-researcher", "summarizer", "image-gen", "transcriber"],
        "advantages": [
            "True drop-in OpenAI API replacement",
            "Multi-modal: text, image, audio, embeddings",
            "Backend-agnostic — pick llama.cpp, vLLM, or diffusers per model",
            "Docker-first with model galleries",
            "Token-based auth and concurrency control",
        ],
        "businessAdvantages": [
            "Self-hosted — no data leaves your network",
            "One API for text + image + audio",
            "Multi-tenant with per-key quotas",
            "MIT license — no vendor lock-in",
        ],
        "apiIntegrationDetails": "POST http://localhost:8080/v1/chat/completions { model, messages } with header `Authorization: Bearer <token>` — OpenAI-compatible.",
    },
    # ── Frameworks & Stacks ─────────────────────────────────────────
    {
        "name": "dify",
        "displayName": "Dify",
        "tagline": "Open-source LLMOps platform — visually build, deploy, and operate AI assistants, agents, and workflows.",
        "icon": "Workflow",
        "color": "#1565c0",
        "category": "orchestration",
        "kind": "platform",
        "popularity": "very-high",
        "bestFor": [
            "Building production AI assistants with a visual workflow editor",
            "Non-developers composing prompt chains and RAG pipelines",
            "Operating LLMOps — observability, A/B testing, and versioning",
            "Self-hosted ChatGPT-like assistants for the enterprise",
        ],
        "capabilities": [
            "Visual workflow builder for prompt chains, RAG, and agents",
            "Built-in RAG pipeline with chunking, embedding, and reranking",
            "Multi-model routing across OpenAI, Anthropic, local models",
            "Audit logs, usage analytics, and per-app API keys",
            "Marketplace of pre-built assistant templates",
        ],
        "whenToUse": [
            "You need a visual builder for AI assistants",
            "You want LLMOps with observability and versioning",
            "Compliance requires self-hosted assistant infrastructure",
        ],
        "limitations": [
            "Self-hosted setup is non-trivial (Docker Compose, Postgres, Redis, vector DB)",
            "Cloud tier has license restrictions for enterprise features",
            "Workflow engine is less flexible than pure code (LangGraph)",
        ],
        "samplePrompts": [
            "Build a Dify workflow that summarizes PDFs and emails the summary",
            "Use Dify's RAG pipeline with Qdrant as the vector store",
            "Deploy Dify on Kubernetes with Helm",
        ],
        "setupNotes": "Self-host with Docker Compose: `git clone https://github.com/langgenius/dify && cd dify/docker && docker compose up -d`. Access on http://localhost:3000. Marq can call Dify's app API to embed Dify-built assistants.",
        "pricingTier": "Free / open source (Apache-2.0); cloud plans from $59/mo",
        "docsUrl": "https://docs.dify.ai",
        "availableModels": ["(any provider Dify supports)", "GPT-4o", "Claude", "Llama 3", "Gemini"],
        "availableAgents": ["dify-assistant", "rag-docs", "summarizer"],
        "advantages": [
            "Visual workflow builder — no code required for assistants",
            "Production-grade LLMOps: logs, metrics, A/B tests",
            "Multi-model with smart routing",
            "Built-in RAG with chunking + reranking",
            "Marketplace of pre-built templates",
        ],
        "businessAdvantages": [
            "Apache-2.0 license — self-host without vendor lock-in",
            "Empowers non-developers to ship assistants",
            "Audit logs for regulated industries",
            "Cloud tier for teams that don't want to self-host",
        ],
        "apiIntegrationDetails": "POST https://api.dify.ai/v1/chat-messages { query, user, conversation_id } with header `Authorization: Bearer app-<key>` — Dify's own API.",
    },
    {
        "name": "litellm",
        "displayName": "LiteLLM",
        "tagline": "Unified OpenAI-compatible proxy for 100+ LLM providers with cost tracking, load balancing, and fallbacks.",
        "icon": "Router",
        "color": "#0ea5e9",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "very-high",
        "bestFor": [
            "Routing between 100+ LLM providers behind one OpenAI API",
            "Cost tracking and budget alerts per project",
            "Load balancing and fallback across providers",
            "Token-based access control for internal teams",
        ],
        "capabilities": [
            "Proxy 100+ providers (OpenAI, Anthropic, Gemini, Bedrock, Azure, Mistral, Cohere, local)",
            "OpenAI-compatible /v1/chat/completions, /v1/embeddings",
            "Per-key budgets, rate limits, and RPM/TPM throttling",
            "Cost tracking with PostgreSQL logging",
            "Fallback chains: A → B → C on error",
        ],
        "whenToUse": [
            "You want a unified API across many providers",
            "You need cost tracking and budgets per team",
            "You're building an internal LLM gateway",
        ],
        "limitations": [
            "Self-hosted proxy adds one more service to operate",
            "Some provider features (e.g., Anthropic prompt caching) need explicit passthrough",
            "Admin UI is less polished than Dify",
        ],
        "samplePrompts": [
            "Deploy LiteLLM proxy with Anthropic + OpenAI + Ollama backends",
            "Set per-key monthly budget of $100 in LiteLLM",
            "Configure LiteLLM fallback: GPT-4o → Claude → Gemini",
        ],
        "setupNotes": "`pip install litellm[proxy]` then `litellm --model claude-sonnet-4-5 --port 4000`. Marq can use the running proxy as a generic OpenAI-compatible provider.",
        "pricingTier": "Free / open source (MIT); managed LiteLLM proxy from $20/mo",
        "docsUrl": "https://docs.litellm.ai",
        "availableModels": ["(100+ providers)", "GPT-4o", "Claude", "Gemini", "Llama 3", "Mistral"],
        "availableAgents": ["any-agent", "router-agent"],
        "advantages": [
            "One API for 100+ providers",
            "Per-key budgets and rate limits",
            "Fallback chains and load balancing",
            "Cost tracking with Postgres logging",
            "Drop-in OpenAI compatibility",
        ],
        "businessAdvantages": [
            "Single gateway for all internal LLM use",
            "Cost visibility per team / project",
            "Fallbacks prevent outages when a provider fails",
            "MIT license + paid managed tier",
        ],
        "apiIntegrationDetails": "POST http://localhost:4000/v1/chat/completions { model, messages } with header `Authorization: Bearer sk-<litellm-key>` — OpenAI-compatible.",
    },
    {
        "name": "llamaindex",
        "displayName": "LlamaIndex",
        "tagline": "Data framework for connecting custom data sources to LLMs — RAG pipelines, document indexes, query engines.",
        "icon": "Database",
        "color": "#6366f1",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "very-high",
        "bestFor": [
            "Production RAG over documents, databases, and APIs",
            "Multi-index query routing (vector + keyword + knowledge graph)",
            "Document-level citations and source tracking",
            "Building data agents that query tools and APIs",
        ],
        "capabilities": [
            "Document loaders for 100+ sources (PDF, Notion, Slack, SQL, etc.)",
            "Vector + keyword + graph index combinations",
            "Query engines with rewriting, routing, and sub-queries",
            "Data agents that call tools and APIs",
            "Evaluation tools (faithfulness, relevancy, context recall)",
        ],
        "whenToUse": [
            "You need production-grade RAG with citations",
            "Your data is split across many sources",
            "You want evaluation metrics on RAG quality",
        ],
        "limitations": [
            "Steeper learning curve than LangChain for simple chains",
            "More opinionated — less flexible for non-RAG use cases",
            "Token costs can balloon with deep query trees",
        ],
        "samplePrompts": [
            "Build a LlamaIndex RAG pipeline over my Notion workspace",
            "Use LlamaIndex SubQuestionQueryEngine for multi-document Q&A",
            "Evaluate my RAG pipeline with LlamaIndex's faithfulness metric",
        ],
        "setupNotes": "`pip install llama-index` then load documents, build a VectorStoreIndex, and query. For Marq integration, expose your query engine as an HTTP endpoint and route to it.",
        "pricingTier": "Free / open source (MIT); LlamaCloud managed from $0.10/k observations",
        "docsUrl": "https://docs.llamaindex.ai",
        "availableModels": ["(any LLM via OpenAI-compatible API)", "GPT-4o", "Claude", "Llama 3"],
        "availableAgents": ["rag-docs", "researcher", "data-agent"],
        "advantages": [
            "100+ document loaders out of the box",
            "Multi-index fusion (vector + keyword + graph)",
            "Built-in evaluation metrics",
            "Sub-question query engine for complex Q&A",
            "Production-grade citation tracking",
        ],
        "businessAdvantages": [
            "Faster time-to-production for RAG features",
            "Built-in evals reduce QA burden",
            "LlamaCloud for teams that want managed indexes",
            "Active community + enterprise support",
        ],
        "apiIntegrationDetails": "Python SDK: `from llama_index.core import VectorStoreIndex, SimpleDirectoryReader; index = VectorStoreIndex.from_documents(SimpleDirectoryReader('./data').load_data()); index.as_query_engine().query('question')`.",
    },
    {
        "name": "dspy",
        "displayName": "DSPy",
        "tagline": "Framework for programming — not prompting — language models. Compile declarative pipelines to optimized prompts.",
        "icon": "Braces",
        "color": "#9333ea",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "high",
        "bestFor": [
            "Replacing hand-written prompts with compiled, optimized ones",
            "Programmatic LLM pipelines with automatic prompt tuning",
            "Research-grade experiments on prompt optimization",
            "Reducing prompt fragility across model upgrades",
        ],
        "capabilities": [
            "Declarative signatures: `class Answer(dspy.Signature): question = dspy.InputField(); answer = dspy.OutputField()`",
            "Optimizers that tune prompts via few-shot bootstrapping",
            "Built-in modules: Predict, ChainOfThought, ReAct, ProgramOfThought",
            "Evaluation harness with metric functions",
            "Multi-model support — compile for one, deploy on another",
        ],
        "whenToUse": [
            "Your hand-tuned prompts break across model versions",
            "You want automatic few-shot example selection",
            "You're doing serious prompt engineering research",
        ],
        "limitations": [
            "Steeper learning curve than LangChain",
            "Compilation can be expensive (many LLM calls)",
            "Smaller community than LangChain",
        ],
        "samplePrompts": [
            "Build a DSPy RAG pipeline with the ReAct module",
            "Use BootstrapFewShot to optimize a DSPy signature",
            "Evaluate a DSPy program with a custom metric",
        ],
        "setupNotes": "`pip install dspy-ai` then define a Signature, wrap it in a Module, and call `module(question='...')`. For optimization, wrap with `BootstrapFewShot` and `.compile()`.",
        "pricingTier": "Free / open source (MIT)",
        "docsUrl": "https://dspy.ai",
        "availableModels": ["(any LLM via litellm)", "GPT-4o", "Claude", "Llama 3"],
        "availableAgents": ["rag-docs", "researcher", "code-reviewer"],
        "advantages": [
            "Prompts become a compilation target — not hand-written",
            "Optimizers auto-select few-shot examples",
            "Compile for GPT-4, deploy on Llama 3",
            "Built-in eval harness",
            "Modular composition (Predict, ReAct, ChainOfThought)",
        ],
        "businessAdvantages": [
            "Reduces prompt-engineering labor cost",
            "Prompts survive model upgrades",
            "Research-grade methodology",
            "Active Stanford research team",
        ],
        "apiIntegrationDetails": "Python SDK: `import dspy; lm = dspy.LM('openai/gpt-4o'); dspy.configure(lm=lm); answer = dspy.Predict('question -> answer')(question='...')`.",
    },
    {
        "name": "langgraph",
        "displayName": "LangGraph",
        "tagline": "Low-level framework for building stateful, long-running AI agents with graph-based orchestration.",
        "icon": "Workflow",
        "color": "#16a34a",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "very-high",
        "bestFor": [
            "Building stateful multi-step agents with cycles",
            "Long-running workflows with human-in-the-loop checkpoints",
            "Multi-agent collaboration with explicit state transitions",
            "Production agents that need observability and replay",
        ],
        "capabilities": [
            "Define agents as stateful graphs (nodes + edges)",
            "Persistence with checkpointers (SQLite, Postgres, Redis)",
            "Human-in-the-loop interrupts and approvals",
            "Sub-graphs and parallel branches",
            "Time travel — replay from any checkpoint",
        ],
        "whenToUse": [
            "Your agent needs cycles (not just linear chains)",
            "You need human approvals mid-workflow",
            "You want checkpointed, resumable agents",
        ],
        "limitations": [
            "More verbose than LangChain's AgentExecutor",
            "Graph DSL takes time to learn",
            "Cloud offering (LangGraph Platform) is separate from OSS",
        ],
        "samplePrompts": [
            "Build a LangGraph agent with a human-in-the-loop approval node",
            "Use LangGraph checkpointing with Postgres for resumable workflows",
            "Define a multi-agent supervisor graph in LangGraph",
        ],
        "setupNotes": "`pip install langgraph` then define `StateGraph(MyState)`, add nodes, add edges, compile. Pair with LangChain tool definitions.",
        "pricingTier": "Free / open source (MIT); LangGraph Platform from $0.10/node-hour",
        "docsUrl": "https://langchain-ai.github.io/langgraph",
        "availableModels": ["(any LLM via LangChain)", "GPT-4o", "Claude", "Llama 3"],
        "availableAgents": ["any-agent", "researcher", "code-reviewer", "multi-step"],
        "advantages": [
            "First-class cycles and conditional edges",
            "Persistent checkpointing for long-running agents",
            "Human-in-the-loop interrupts",
            "Sub-graphs and parallel branches",
            "Time-travel debugging",
        ],
        "businessAdvantages": [
            "Production-grade stateful agents",
            "Replayable workflows aid debugging and compliance",
            "LangGraph Platform for managed hosting",
            "Active LangChain ecosystem",
        ],
        "apiIntegrationDetails": "Python SDK: `from langgraph.graph import StateGraph; graph = StateGraph(State); graph.add_node('step1', fn); graph.add_edge('step1', 'step2'); app = graph.compile(checkpointer=...); app.invoke(input)`.",
    },
    {
        "name": "semantic-kernel",
        "displayName": "Semantic Kernel",
        "tagline": "Microsoft's SDK for building and orchestrating AI agents in .NET, Python, and Java — first-class C# support.",
        "icon": "Brain",
        "color": "#0078d4",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "high",
        "bestFor": [
            "Building AI agents in .NET / C# enterprise stacks",
            "Plugin-based agent composition with semantic functions",
            "Microsoft Azure OpenAI integration",
            "Cross-language agents (.NET + Python + Java)",
        ],
        "capabilities": [
            "Semantic functions (prompts) and native functions (code) as plugins",
            "Planner that auto-selects plugins to achieve a goal",
            "First-class Azure OpenAI, OpenAI, and local model connectors",
            "Memory: embeddings, semantic memory, volatile/persistent stores",
            "Filters and middleware for telemetry and governance",
        ],
        "whenToUse": [
            "Your stack is .NET / Azure",
            "You want Microsoft's supported AI SDK",
            "Plugin-based agent composition fits your architecture",
        ],
        "limitations": [
            "Smaller community than LangChain in Python land",
            "Less polished Python/Java experience vs .NET",
            "Planner can be unpredictable without tuning",
        ],
        "samplePrompts": [
            "Build a Semantic Kernel plugin that calls a REST API",
            "Use the Semantic Kernel planner to chain plugins for a goal",
            "Integrate Semantic Kernel with Azure OpenAI for an enterprise chatbot",
        ],
        "setupNotes": ".NET: `dotnet add package Microsoft.SemanticKernel`. Python: `pip install semantic-kernel`. Define plugins, register with a Kernel, invoke.",
        "pricingTier": "Free / open source (MIT)",
        "docsUrl": "https://learn.microsoft.com/semantic-kernel",
        "availableModels": ["Azure OpenAI", "OpenAI", "Hugging Face", "Ollama", "ONNX"],
        "availableAgents": ["planner-agent", "researcher", "code-reviewer"],
        "advantages": [
            "Best-in-class .NET / C# AI SDK",
            "First-class Azure OpenAI integration",
            "Plugin architecture with semantic + native functions",
            "Auto-planning for goal-driven agent execution",
            "Microsoft-supported with LTS releases",
        ],
        "businessAdvantages": [
            "Microsoft support — enterprise SLA friendly",
            "Fits .NET / Azure stacks without bridging",
            "Plugin marketplace internally",
            "Open source (MIT) but with commercial support path",
        ],
        "apiIntegrationDetails": ".NET: `var kernel = Kernel.Builder.WithAzureOpenAIChatCompletion(...).Build(); await kernel.InvokeAsync(function, args)`. Python: similar API.",
    },
    {
        "name": "vercel-ai-sdk",
        "displayName": "Vercel AI SDK",
        "tagline": "TypeScript toolkit for building AI applications with streaming, tool calling, and agents — the React way.",
        "icon": "Triangle",
        "color": "#000000",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "very-high",
        "bestFor": [
            "Streaming AI responses in Next.js / React apps",
            "Type-safe tool calling and structured outputs",
            "Multi-provider switching without code changes",
            "Edge-deployed AI endpoints on Vercel",
        ],
        "capabilities": [
            "`streamText`, `generateText`, `generateObject` core functions",
            "100+ provider adapters (OpenAI, Anthropic, Google, Mistral, Cohere, etc.)",
            "Tool calling with Zod schema validation",
            "React hooks: `useChat`, `useObject`, `useCompletion`",
            "Edge runtime support for global low-latency",
        ],
        "whenToUse": [
            "You're building a Next.js / React AI app",
            "You need streaming UX with tool calls",
            "You deploy on Vercel or any edge runtime",
        ],
        "limitations": [
            "TypeScript-only — no Python",
            "Provider feature gaps require adapter updates",
            "Some advanced agent patterns need custom code",
        ],
        "samplePrompts": [
            "Build a streaming chat UI with the Vercel AI SDK and Next.js App Router",
            "Use generateObject with Zod to get typed JSON from an LLM",
            "Define a tool the AI can call to query your database",
        ],
        "setupNotes": "`npm install ai @ai-sdk/openai @ai-sdk/anthropic` then `import { streamText } from 'ai'; import { openai } from '@ai-sdk/openai'; const { textStream } = streamText({ model: openai('gpt-4o'), prompt });`.",
        "pricingTier": "Free / open source (Apache-2.0)",
        "docsUrl": "https://sdk.vercel.ai/docs",
        "availableModels": ["(100+ providers via @ai-sdk/* packages)", "GPT-4o", "Claude", "Gemini"],
        "availableAgents": ["any-ts-agent", "chat-ui", "structured-output"],
        "advantages": [
            "First-class TypeScript / React experience",
            "Streaming + tool calling + structured outputs in one SDK",
            "100+ provider adapters",
            "Edge runtime support",
            "Active Vercel-backed development",
        ],
        "businessAdvantages": [
            "Reduces frontend AI dev time",
            "Provider-agnostic — switch without rewrites",
            "Edge-deployable for global low latency",
            "Apache-2.0 — free for commercial use",
        ],
        "apiIntegrationDetails": "TypeScript: `import { streamText, openai } from 'ai'; const result = streamText({ model: openai('gpt-4o'), messages }); for await (const chunk of result.textStream) console.log(chunk);`.",
    },
    {
        "name": "mastra",
        "displayName": "Mastra",
        "tagline": "TypeScript-first AI framework for building agents, RAG pipelines, and workflows — batteries-included.",
        "icon": "Boxes",
        "color": "#f97316",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "high",
        "bestFor": [
            "TypeScript teams wanting an opinionated agent framework",
            "RAG + agent workflows in one framework",
            "Building evals and agent tests in TS",
            "Self-hosted agent infrastructure",
        ],
        "capabilities": [
            "Agent definitions with tools, memory, and workflows",
            "RAG pipeline with chunking, embedding, vector storage",
            "Built-in eval framework",
            "Workflow engine with steps, branches, and suspends",
            "Vercel AI SDK integration under the hood",
        ],
        "whenToUse": [
            "You want a batteries-included TS framework (vs assembling Vercel AI SDK pieces)",
            "You need both agents and RAG in one stack",
            "You want built-in evals",
        ],
        "limitations": [
            "Younger project than LangChain",
            "Smaller plugin ecosystem",
            "Documentation still maturing",
        ],
        "samplePrompts": [
            "Build a Mastra agent with web search and file tools",
            "Use Mastra's workflow engine for a multi-step approval flow",
            "Set up RAG over my docs with Mastra",
        ],
        "setupNotes": "`npm install @mastra/core` then define an Agent with `new Agent({ name, instructions, model, tools })`.",
        "pricingTier": "Free / open source (Apache-2.0)",
        "docsUrl": "https://mastra.ai/docs",
        "availableModels": ["(any Vercel AI SDK provider)", "GPT-4o", "Claude", "Llama 3"],
        "availableAgents": ["any-ts-agent", "rag-docs", "workflow"],
        "advantages": [
            "TypeScript-native agent + RAG framework",
            "Built-in eval framework",
            "Workflow engine with suspends and approvals",
            "Batteries-included — fewer glue packages needed",
            "Vercel AI SDK under the hood for provider support",
        ],
        "businessAdvantages": [
            "Faster TS agent development",
            "Self-hostable — no vendor lock-in",
            "Apache-2.0 license",
            "Active team and growing ecosystem",
        ],
        "apiIntegrationDetails": "TypeScript: `import { Agent } from '@mastra/core'; const agent = new Agent({ name: 'researcher', instructions: '...', model, tools }); const result = await agent.generate('question');`.",
    },
    {
        "name": "pydantic-ai",
        "displayName": "Pydantic AI",
        "tagline": "Type-safe Python agent framework with Pydantic validation, tool calling, and dependency injection.",
        "icon": "ShieldCheck",
        "color": "#e92063",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "high",
        "bestFor": [
            "Type-safe Python agents with validated inputs and outputs",
            "Dependency injection for testable agent code",
            "Structured outputs with Pydantic models",
            "Teams already using FastAPI / Pydantic",
        ],
        "capabilities": [
            "Define agents with typed result models (Pydantic)",
            "Tools with typed args and validated returns",
            "Dependency injection for DBs, APIs, etc.",
            "Multi-model: OpenAI, Anthropic, Gemini, Groq, Ollama, etc.",
            "Built-in usage limits and token tracking",
        ],
        "whenToUse": [
            "You want type-safe agent I/O in Python",
            "Your team already uses Pydantic / FastAPI",
            "You need dependency injection for testable agents",
        ],
        "limitations": [
            "Younger than LangChain — smaller plugin ecosystem",
            "Python only",
            "Some agent patterns still require custom code",
        ],
        "samplePrompts": [
            "Build a Pydantic AI agent with a typed result model",
            "Use dependency injection in Pydantic AI to inject a database client",
            "Define a tool with typed args in Pydantic AI",
        ],
        "setupNotes": "`pip install pydantic-ai` then `from pydantic_ai import Agent; agent = Agent('openai:gpt-4o', result_type=MyModel); result = agent.run_sync('question')`.",
        "pricingTier": "Free / open source (MIT)",
        "docsUrl": "https://ai.pydantic.dev",
        "availableModels": ["OpenAI", "Anthropic", "Gemini", "Groq", "Ollama", "Mistral"],
        "availableAgents": ["any-py-agent", "researcher", "structured-output"],
        "advantages": [
            "Type-safe agent I/O with Pydantic",
            "Dependency injection for clean testing",
            "Structured outputs as Pydantic models",
            "Multi-model support",
            "Token tracking built in",
        ],
        "businessAdvantages": [
            "Type safety reduces production bugs",
            "Fits existing FastAPI / Pydantic stacks",
            "MIT licensed",
            "Active Pydantic team — same maintainers as FastAPI",
        ],
        "apiIntegrationDetails": "Python: `from pydantic_ai import Agent; agent = Agent('openai:gpt-4o', result_type=MyModel); result = await agent.run('question')`.",
    },
    {
        "name": "spring-ai",
        "displayName": "Spring AI",
        "tagline": "Spring framework for building AI-powered Java applications — portable model and vector store abstractions.",
        "icon": "Leaf",
        "color": "#6db33f",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "medium",
        "bestFor": [
            "Java / Spring Boot teams adding AI features",
            "Portable model + vector store abstractions",
            "Enterprise Java stacks already on Spring",
            "Function calling and RAG in idiomatic Spring",
        ],
        "capabilities": [
            "ChatClient — fluent API for chat completions",
            "VectorStore abstraction (PgVector, Redis, Chroma, Pinecone, Weaviate, etc.)",
            "Tool/function calling via @Bean-registered functions",
            "Structured output via `entity(Class<T>)`",
            "Advisors for RAG, prompt templating, logging",
        ],
        "whenToUse": [
            "Your stack is Spring Boot / Java",
            "You want portable model + vector store abstractions",
            "Enterprise Java integration is critical",
        ],
        "limitations": [
            "Java-only",
            "Smaller community than Python frameworks",
            "Lags behind Python frameworks in bleeding-edge features",
        ],
        "samplePrompts": [
            "Build a Spring AI ChatClient with OpenAI",
            "Implement RAG with Spring AI and PgVector",
            "Register a function tool in Spring AI",
        ],
        "setupNotes": "Maven: `<dependency><groupId>org.springframework.ai</groupId><artifactId>spring-ai-openai-spring-boot-starter</artifactId></dependency>`. Configure `spring.ai.openai.api-key=...` in application.properties.",
        "pricingTier": "Free / open source (Apache-2.0)",
        "docsUrl": "https://docs.spring.io/spring-ai",
        "availableModels": ["OpenAI", "Anthropic", "Azure OpenAI", "Ollama", "Mistral", "Vertex AI"],
        "availableAgents": ["any-java-agent", "rag-docs"],
        "advantages": [
            "Idiomatic Spring Boot integration",
            "Portable model + vector store abstractions",
            "Tool calling via Spring beans",
            "Structured output as POJOs",
            "Enterprise-ready — fits existing Spring stacks",
        ],
        "businessAdvantages": [
            "No need to introduce Python for AI features",
            "Fits enterprise Java investments",
            "Apache-2.0 license",
            "VMware / Spring team supported",
        ],
        "apiIntegrationDetails": "Java: `@Bean ChatClient chatClient(ChatClient.Builder b) { return b.build(); } chatClient.prompt('question').call().content()`.",
    },
    {
        "name": "haystack",
        "displayName": "Haystack",
        "tagline": "Production-ready open-source AI framework by deepset — RAG pipelines, document search, and conversational agents.",
        "icon": "Search",
        "color": "#5b21b6",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "high",
        "bestFor": [
            "Production RAG pipelines with strong evals",
            "Document search (keyword + dense) at scale",
            "Conversational QA over enterprise documents",
            "Pipelines that need to be serialized and versioned",
        ],
        "capabilities": [
            "YAML-serializable pipelines (version + diff)",
            "Connectors for 100+ document stores (Elasticsearch, OpenSearch, Weaviate, Qdrant, Pinecone, etc.)",
            "Hybrid retrieval (BM25 + dense)",
            "Rerankers (Cohere, SentenceTransformers, etc.)",
            "Haystack Eval: retrieval + answer quality metrics",
        ],
        "whenToUse": [
            "You need production-grade RAG with strong evals",
            "Your team already uses deepset or Elasticsearch",
            "Pipelines need versioning + reproducibility",
        ],
        "limitations": [
            "More opinionated than LangChain",
            "Less flexible for non-RAG agents",
            "Documentation assumes RAG context",
        ],
        "samplePrompts": [
            "Build a Haystack hybrid retrieval RAG pipeline",
            "Use Haystack's Eval to measure retrieval recall@k",
            "Connect Haystack to Elasticsearch with BM25 + dense",
        ],
        "setupNotes": "`pip install haystack-ai` then define a Pipeline with `DocumentStore`, `Retriever`, `Reader` (or `PromptNode`) components.",
        "pricingTier": "Free / open source (Apache-2.0); deepset Cloud managed",
        "docsUrl": "https://haystack.deepset.ai",
        "availableModels": ["(any LLM via Hugging Face or OpenAI)", "GPT-4o", "Claude", "Llama 3"],
        "availableAgents": ["rag-docs", "researcher", "search-agent"],
        "advantages": [
            "YAML-serializable, versionable pipelines",
            "100+ document store connectors",
            "Hybrid retrieval (BM25 + dense)",
            "Built-in eval framework",
            "Production-proven at scale",
        ],
        "businessAdvantages": [
            "Reproducible, auditable pipelines",
            "deepset Cloud for managed hosting",
            "Apache-2.0 license",
            "Used in production by large enterprises",
        ],
        "apiIntegrationDetails": "Python: `from haystack import Pipeline; pipe = Pipeline(); pipe.add_component('retriever', ...); pipe.run({'query': 'question'})`.",
    },
    {
        "name": "phidata",
        "displayName": "Phidata",
        "tagline": "Build AI apps in minutes with pre-built templates — agents, RAG, and workflows for fast prototyping.",
        "icon": "Zap",
        "color": "#dc2626",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "high",
        "bestFor": [
            "Fast prototyping of AI assistants with templates",
            "Building agents with memory, tools, and knowledge",
            "Pre-built templates for common use cases",
            "Teams wanting opinionated defaults",
        ],
        "capabilities": [
            "Agent class with memory, tools, and knowledge bases",
            "Pre-built templates (analyst, researcher, coder, etc.)",
            "Knowledge base with auto-embedding",
            "Sessions and user-level memory",
            "Streamlit / FastAPI integration for quick UIs",
        ],
        "whenToUse": [
            "You want pre-built agent templates to start fast",
            "You need agents with persistent memory + knowledge",
            "Opinionated defaults save time",
        ],
        "limitations": [
            "Less flexible than LangGraph for custom graphs",
            "Templates can be too opinionated",
            "Younger community",
        ],
        "samplePrompts": [
            "Build a research agent with Phidata in 10 lines",
            "Use Phidata's knowledge base with my PDFs",
            "Deploy a Phidata agent behind a FastAPI endpoint",
        ],
        "setupNotes": "`pip install phidata` then `from phi.agent import Agent; agent = Agent(model='gpt-4o', tools=[...]); agent.print_response('question')`.",
        "pricingTier": "Free / open source (MPL-2.0); Phidata Cloud managed",
        "docsUrl": "https://docs.phidata.com",
        "availableModels": ["OpenAI", "Anthropic", "Groq", "Ollama", "Mistral"],
        "availableAgents": ["analyst", "researcher", "coder", "rag-docs"],
        "advantages": [
            "Pre-built agent templates for fast starts",
            "Built-in memory + knowledge base",
            "Streamlit / FastAPI integration",
            "Multi-model support",
            "Opinionated defaults reduce boilerplate",
        ],
        "businessAdvantages": [
            "Faster time-to-prototype",
            "MPL-2.0 license",
            "Phidata Cloud for managed hosting",
            "Active development",
        ],
        "apiIntegrationDetails": "Python: `from phi.agent import Agent; agent = Agent(model='gpt-4o'); agent.print_response('question', stream=True)`.",
    },
    {
        "name": "google-adk",
        "displayName": "Google ADK",
        "tagline": "Open-source Agent Development Kit from Google for building multi-agent systems with Gemini and Vertex AI.",
        "icon": "Network",
        "color": "#4285f4",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "high",
        "bestFor": [
            "Building multi-agent systems with Google Gemini",
            "Vertex AI integration with managed serving",
            "Agents with tools, memory, and sub-agents",
            "Google Cloud-native deployments",
        ],
        "capabilities": [
            "Define agents with `Agent(model, tools, sub_agents)`",
            "First-class Gemini and Vertex AI integration",
            "Built-in session and state management",
            "Tool definitions for Python functions",
            "Vertex AI Agent Builder deployment",
        ],
        "whenToUse": [
            "You're committed to Google Cloud / Gemini",
            "You need managed multi-agent serving",
            "You want Google-supported agent tooling",
        ],
        "limitations": [
            "Google Cloud lock-in for managed features",
            "Younger than LangChain / CrewAI",
            "Best features tied to Vertex AI paid tier",
        ],
        "samplePrompts": [
            "Build a multi-agent system with Google ADK and Gemini",
            "Deploy an ADK agent to Vertex AI Agent Builder",
            "Define a Python tool callable by an ADK agent",
        ],
        "setupNotes": "`pip install google-adk` then define agents with `from google.adk import Agent; agent = Agent(model='gemini-2.0-flash', tools=[my_tool])`.",
        "pricingTier": "Free / open source (Apache-2.0); Vertex AI usage fees apply",
        "docsUrl": "https://google.github.io/adk-docs",
        "availableModels": ["Gemini 2.0 Flash", "Gemini 2.5 Pro", "Vertex AI models"],
        "availableAgents": ["multi-agent", "researcher", "any-agent"],
        "advantages": [
            "First-class Gemini + Vertex AI integration",
            "Multi-agent orchestration built in",
            "Session and state management",
            "Tool definitions for Python functions",
            "Google-supported with active roadmap",
        ],
        "businessAdvantages": [
            "Fits Google Cloud stacks",
            "Managed deployment via Vertex AI Agent Builder",
            "Apache-2.0 license",
            "Backed by Google engineering",
        ],
        "apiIntegrationDetails": "Python: `from google.adk import Agent; agent = Agent(model='gemini-2.0-flash', tools=[...]); result = agent.run('question')`.",
    },
    {
        "name": "stagehand",
        "displayName": "Stagehand",
        "tagline": "AI-powered browser automation framework with natural language actions, extraction, and observation.",
        "icon": "MousePointerClick",
        "color": "#0ea5e9",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "medium",
        "bestFor": [
            "Natural-language browser automation (Playwright + LLM)",
            "Extracting structured data from any web page",
            "AI agents that browse and act on the web",
            "Replacing brittle CSS selectors with LLM intent",
        ],
        "capabilities": [
            "`page.act('click the login button')` — natural language actions",
            "`page.extract({ schema: ZodSchema })` — typed extraction",
            "`page.observe()` — let the LLM describe what's clickable",
            "Playwright under the hood — full browser control",
            "Multi-model: OpenAI, Anthropic, Gemini",
        ],
        "whenToUse": [
            "CSS selectors keep breaking on UI changes",
            "You need to scrape structured data from many sites",
            "AI agents need to browse the web",
        ],
        "limitations": [
            "LLM calls add latency and cost per action",
            "Younger than Playwright / Puppeteer",
            "Best for low-volume high-flexibility use cases",
        ],
        "samplePrompts": [
            "Build a Stagehand script that books a flight",
            "Extract product prices from a competitor's site with Stagehand",
            "Use Stagehand.observe() to let an agent decide what to click",
        ],
        "setupNotes": "`npm install @browserbasehq/stagehand` then `import { Stagehand } from '@browserbasehq/stagehand'; const stagehand = new Stagehand({ env: 'LOCAL' }); await stagehand.page.goto('https://example.com'); await stagehand.page.act('click login');`",
        "pricingTier": "Free / open source (MIT); Browserbase cloud from $39/mo",
        "docsUrl": "https://docs.stagehand.dev",
        "availableModels": ["OpenAI", "Anthropic", "Gemini"],
        "availableAgents": ["browser-agent", "scraper", "researcher"],
        "advantages": [
            "Natural language browser actions — no brittle selectors",
            "Typed extraction with Zod schemas",
            "Playwright-compatible",
            "Multi-model LLM support",
            "Browserbase for managed cloud browsers",
        ],
        "businessAdvantages": [
            "Survives UI changes that break traditional scrapers",
            "Faster agent development for web tasks",
            "MIT license",
            "Browserbase removes captcha / proxy headaches",
        ],
        "apiIntegrationDetails": "TypeScript: `import { Stagehand } from '@browserbasehq/stagehand'; const sh = new Stagehand(); await sh.page.goto(url); await sh.page.act('click the submit button');`",
    },
    {
        "name": "tanstack-ai",
        "displayName": "TanStack AI",
        "tagline": "Framework-agnostic TypeScript library for AI chat, streaming, tools, and structured outputs.",
        "icon": "Braces",
        "color": "#18181b",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "medium",
        "bestFor": [
            "Framework-agnostic TS chat / streaming UIs",
            "React, Solid, Svelte, Vue — same API",
            "Type-safe tool calling and structured outputs",
            "Teams already invested in TanStack Router / Query",
        ],
        "capabilities": [
            "`useChat` hook with framework-agnostic core",
            "Streaming text + tool calls",
            "Typed message streams with Zod",
            "Adapter pattern — bring your own LLM client",
            "Works with TanStack Router / Query",
        ],
        "whenToUse": [
            "You're not on React (Solid, Svelte, Vue)",
            "You want framework-agnostic AI hooks",
            "You already use TanStack ecosystem",
        ],
        "limitations": [
            "Younger than Vercel AI SDK",
            "Smaller provider adapter ecosystem",
            "Some patterns still experimental",
        ],
        "samplePrompts": [
            "Build a chat UI with TanStack AI and Solid.js",
            "Use TanStack AI's tool calling with Zod schemas",
            "Stream structured output from an LLM with TanStack AI",
        ],
        "setupNotes": "`npm install @tanstack/ai-core` plus the React/Solid/Svelte adapter. Then `import { useChat } from '@tanstack/react-ai'; const { messages, sendMessage } = useChat();`",
        "pricingTier": "Free / open source (MIT)",
        "docsUrl": "https://ai.tanstack.com",
        "availableModels": ["(any LLM via adapter)", "OpenAI", "Anthropic", "Ollama"],
        "availableAgents": ["any-ts-agent", "chat-ui"],
        "advantages": [
            "Framework-agnostic — React, Solid, Svelte, Vue",
            "Type-safe tool calling",
            "Adapter pattern — no vendor lock-in",
            "Fits TanStack ecosystem",
            "MIT licensed",
        ],
        "businessAdvantages": [
            "Reuse across frameworks",
            "No vendor lock-in",
            "MIT license",
            "Active TanStack team",
        ],
        "apiIntegrationDetails": "TypeScript: `import { useChat } from '@tanstack/react-ai'; const { messages, sendMessage } = useChat({ api: '/api/chat' });`",
    },
    {
        "name": "modular",
        "displayName": "Modular (Mojo)",
        "tagline": "A modern AI software stack rebuilt from the ground up — Mojo language + MAX engine for any AI pipeline on any hardware.",
        "icon": "Boxes",
        "color": "#f97316",
        "category": "orchestration",
        "kind": "platform",
        "popularity": "medium",
        "bestFor": [
            "Performance-critical AI inference across hardware",
            "Unified runtime for TF, PyTorch, and ONNX models",
            "Mojo language for systems-level ML engineering",
            "Edge + cloud deployment from one stack",
        ],
        "capabilities": [
            "MAX (Modular Acceleration Xperience) engine — runs TF/PyTorch/ONNX models faster",
            "Mojo language — Python superset with systems performance",
            "Unified inference server — OpenAI-compatible",
            "Hardware portability: NVIDIA, AMD, Apple, CPU",
            "No code changes to deploy models across backends",
        ],
        "whenToUse": [
            "Inference latency or cost is a bottleneck",
            "You need one runtime for mixed TF + PyTorch + ONNX",
            "You're interested in Mojo for systems ML work",
        ],
        "limitations": [
            "Mojo is still maturing",
            "Smaller ecosystem than PyTorch",
            "Some MAX features require commercial license",
        ],
        "samplePrompts": [
            "Run a Llama 3 model with Modular MAX",
            "Use Mojo to write a custom ML kernel",
            "Serve a PyTorch model via MAX's inference server",
        ],
        "setupNotes": "`pip install modular` then `from modular.max import engine; ...` OR use the MAX inference server. Marq can route to MAX's OpenAI-compatible endpoint.",
        "pricingTier": "Free for personal/research; commercial MAX license for enterprise",
        "docsUrl": "https://docs.modular.com",
        "availableModels": ["Llama 3", "Mistral", "(any TF/PyTorch/ONNX model)"],
        "availableAgents": ["inference-server", "any-agent"],
        "advantages": [
            "Single runtime for TF + PyTorch + ONNX",
            "Mojo — Python superset with systems performance",
            "Hardware portability without code changes",
            "OpenAI-compatible inference server",
            "Performance gains over stock runtimes",
        ],
        "businessAdvantages": [
            "Lower inference cost per token",
            "One runtime across teams and hardware",
            "Mojo retains Python talent",
            "Modular-backed with commercial support",
        ],
        "apiIntegrationDetails": "MAX inference server exposes an OpenAI-compatible API. `POST http://localhost:8000/v1/chat/completions { model, messages }`.",
    },
    {
        "name": "burr",
        "displayName": "Burr",
        "tagline": "Build stateful AI agents and applications as state machines — with a built-in tracing UI.",
        "icon": "Workflow",
        "color": "#65a30d",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "medium",
        "bestFor": [
            "Stateful agents expressed as explicit state machines",
            "Replayable, debuggable agent transitions",
            "Built-in tracing UI for visibility",
            "Production agents that need durable state",
        ],
        "capabilities": [
            "Define agents as state + actions + transitions",
            "Persistent state via Redis, SQLAlchemy, etc.",
            "Built-in tracer with web UI",
            "Streaming + human-in-the-loop interrupts",
            "Multi-agent via sub-state-machines",
        ],
        "whenToUse": [
            "You think in state machines, not graphs",
            "You want a built-in tracer without external observability stack",
            "Replayability is critical for debugging",
        ],
        "limitations": [
            "Smaller community than LangGraph",
            "State-machine DSL takes learning",
            "Less polished docs",
        ],
        "samplePrompts": [
            "Build a Burr state machine for a multi-step research agent",
            "Use Burr's tracer UI to debug an agent",
            "Persist Burr state in Postgres",
        ],
        "setupNotes": "`pip install burr` then `from burr.core import Application, action; app = Application(actions=[...], transitions=[...]).build()`.",
        "pricingTier": "Free / open source (Apache-2.0)",
        "docsUrl": "https://burr.dagworks.io",
        "availableModels": ["(any LLM via OpenAI-compatible)", "GPT-4o", "Claude", "Llama 3"],
        "availableAgents": ["stateful-agent", "researcher"],
        "advantages": [
            "Explicit state machines — clearer than implicit graphs",
            "Built-in tracer with web UI",
            "Persistent state via multiple backends",
            "Streaming + human-in-the-loop",
            "Replayable for debugging",
        ],
        "businessAdvantages": [
            "Auditable state transitions",
            "Built-in observability saves tooling cost",
            "Apache-2.0 license",
            "Active DAGWorks team",
        ],
        "apiIntegrationDetails": "Python: `from burr.core import ApplicationBuilder; app = ApplicationBuilder().with_actions(step1, step2).with_transitions(('step1','step2')).build(); app.run(halt_after=['step2'])`.",
    },
    {
        "name": "ms-agent-framework",
        "displayName": "Microsoft Agent Framework",
        "tagline": "Build agents and graph-based multi-agent workflows in .NET and Python — Microsoft's next-gen agent SDK.",
        "icon": "Workflow",
        "color": "#0078d4",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "medium",
        "bestFor": [
            "Microsoft-stack teams building production agents",
            "Graph-based multi-agent workflows in .NET",
            "Teams moving from Semantic Kernel to a newer MS SDK",
            "Azure-native agent deployments",
        ],
        "capabilities": [
            "Agent definitions with tools and chat",
            "Graph-based multi-agent orchestration",
            "First-class Azure OpenAI + Foundry integration",
            "Stateful conversations with thread management",
            ".NET + Python SDKs",
        ],
        "whenToUse": [
            "You're on .NET and want the newest MS agent SDK",
            "Graph-based multi-agent workflows",
            "You use Azure AI Foundry",
        ],
        "limitations": [
            "Newer than Semantic Kernel — smaller ecosystem",
            "Some features Azure-only",
            "Docs still maturing",
        ],
        "samplePrompts": [
            "Build a Microsoft Agent Framework graph with two agents",
            "Use Microsoft Agent Framework with Azure AI Foundry",
            "Define a tool for an MS Agent Framework agent",
        ],
        "setupNotes": ".NET: `dotnet add package Microsoft.Agents.Abstractions`. Python: `pip install microsoft-agents-core`. Define `Agent` instances and compose via `AgentThread`.",
        "pricingTier": "Free / open source (MIT)",
        "docsUrl": "https://learn.microsoft.com/agent-framework",
        "availableModels": ["Azure OpenAI", "OpenAI", "(any OpenAI-compatible)"],
        "availableAgents": ["any-agent", "multi-agent"],
        "advantages": [
            "Newest Microsoft agent SDK",
            "Graph-based multi-agent orchestration",
            "First-class Azure OpenAI + Foundry",
            ".NET + Python support",
            "Thread management built in",
        ],
        "businessAdvantages": [
            "Microsoft-supported for enterprise",
            "Fits Azure AI Foundry workflows",
            "MIT license",
            "Active Microsoft engineering",
        ],
        "apiIntegrationDetails": ".NET: `var agent = new ChatCompletionAgent { Name='a', Instructions='...' }; await agent.InvokeAsync(thread);`",
    },
    {
        "name": "langroid",
        "displayName": "Langroid",
        "tagline": "Multi-agent LLM framework using message-based task delegation inspired by the Actor model.",
        "icon": "Bot",
        "color": "#0d9488",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "medium",
        "bestFor": [
            "Multi-agent systems with actor-model delegation",
            "Task decomposition across specialized agents",
            "Tool-augmented agents with shared state",
            "Teams wanting a clean multi-agent abstraction",
        ],
        "capabilities": [
            "Agent class with LLM, tools, and message handling",
            "Task — a delegation unit agents can `ask` and `run`",
            "Multi-agent orchestration via message passing",
            "Vector-store integration for RAG",
            "Pydantic-typed tool args and results",
        ],
        "whenToUse": [
            "You think in actors / message passing",
            "Multi-agent task decomposition fits your problem",
            "You want clean multi-agent abstractions",
        ],
        "limitations": [
            "Smaller community than LangChain",
            "Less enterprise tooling",
            "Python only",
        ],
        "samplePrompts": [
            "Build a Langroid multi-agent system with a researcher and a coder",
            "Use Langroid's Task.ask() for inter-agent delegation",
            "Add a tool to a Langroid agent",
        ],
        "setupNotes": "`pip install langroid` then `import langroid as lr; agent = lr.ChatAgent(config); agent.run('question')`.",
        "pricingTier": "Free / open source (MIT)",
        "docsUrl": "https://langroid.github.io/langroid",
        "availableModels": ["OpenAI", "Anthropic", "Ollama", "Mistral", "(any OpenAI-compatible)"],
        "availableAgents": ["multi-agent", "researcher", "coder"],
        "advantages": [
            "Clean actor-model multi-agent abstraction",
            "Task.ask() / Task.run() for delegation",
            "Pydantic-typed tools",
            "Built-in RAG with vector stores",
            "MIT licensed",
        ],
        "businessAdvantages": [
            "Multi-agent systems without framework sprawl",
            "Clean abstractions speed up development",
            "MIT license",
            "Active research-driven team",
        ],
        "apiIntegrationDetails": "Python: `import langroid as lr; agent = lr.ChatAgent(lr.ChatAgentConfig()); result = agent.run('question')`.",
    },
    {
        "name": "llmkit",
        "displayName": "llmkit",
        "tagline": "One LLM client API for 20+ providers, in Go, TypeScript, Python, and Rust — unified interface across languages.",
        "icon": "Braces",
        "color": "#475569",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "low",
        "bestFor": [
            "Polyglot teams needing the same LLM client across Go/TS/Py/Rust",
            "Swapping providers without changing client code",
            "Lightweight — no framework overhead",
            "Standardized chat + embeddings interface",
        ],
        "capabilities": [
            "Unified chat + embeddings interface across 20+ providers",
            "Same API in Go, TypeScript, Python, Rust",
            "Streaming support",
            "Tool calling where provider supports it",
            "Minimal dependencies",
        ],
        "whenToUse": [
            "You have multiple language stacks",
            "You want a thin client, not a framework",
            "Provider portability is critical",
        ],
        "limitations": [
            "Smaller community than LangChain",
            "Fewer integrations than Vercel AI SDK",
            "Documentation thinner",
        ],
        "samplePrompts": [
            "Use llmkit to call OpenAI and Anthropic with the same code",
            "Swap providers at runtime with llmkit",
            "Use llmkit's Rust client for an edge inference app",
        ],
        "setupNotes": "Install per language: Go `go get github.com/llmkit/llmkit-go`, TS `npm install @llmkit/llmkit`, Py `pip install llmkit`, Rust `cargo add llmkit`. Then instantiate a provider and call `.chat(...)`.",
        "pricingTier": "Free / open source (MIT)",
        "docsUrl": "https://github.com/llmkit/llmkit",
        "availableModels": ["OpenAI", "Anthropic", "Google", "Mistral", "Cohere", "20+ providers"],
        "availableAgents": ["any-agent"],
        "advantages": [
            "Same API across Go, TS, Python, Rust",
            "Thin client — no framework lock-in",
            "20+ provider adapters",
            "Streaming + tool calling",
            "MIT licensed",
        ],
        "businessAdvantages": [
            "Polyglot teams share one client API",
            "Provider portability reduces lock-in",
            "Lightweight — minimal attack surface",
            "MIT license",
        ],
        "apiIntegrationDetails": "Go: `client := llmkit.New('openai', apiKey); resp, _ := client.Chat(ctx, llmkit.ChatRequest{Messages: [...]})`. TS/Py/Rust: same shape.",
    },
    {
        "name": "cc-switch",
        "displayName": "CC Switch",
        "tagline": "Open-source desktop manager and local router for AI coding tools — switch between Claude Code, Cursor, and more.",
        "icon": "ToggleLeft",
        "color": "#a855f7",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "low",
        "bestFor": [
            "Switching between AI coding assistants (Claude Code, Cursor, etc.)",
            "Routing coding-agent requests through a local proxy",
            "Managing multiple API keys per tool",
            "Cost tracking per coding session",
        ],
        "capabilities": [
            "Local proxy that routes coding-agent requests to the right provider",
            "Multi-key rotation per provider (avoid rate limits)",
            "Per-session cost tracking",
            "Desktop UI for switching active agent",
            "OpenAI-compatible upstream interface",
        ],
        "whenToUse": [
            "You use multiple AI coding tools and want one router",
            "You need to rotate API keys to avoid rate limits",
            "You want per-session cost visibility for coding tools",
        ],
        "limitations": [
            "Niche use case — coding tools only",
            "Small community",
            "Desktop app — no headless server",
        ],
        "samplePrompts": [
            "Route Claude Code and Cursor through CC Switch",
            "Set up API key rotation in CC Switch",
            "Track per-session spend with CC Switch",
        ],
        "setupNotes": "Download from the project's GitHub releases, install, and configure API keys in Settings. Point your coding tools at the local proxy URL CC Switch exposes.",
        "pricingTier": "Free / open source (MIT)",
        "docsUrl": "https://github.com/farion1231/cc-switch",
        "availableModels": ["OpenAI", "Anthropic", "(any provider the underlying tool supports)"],
        "availableAgents": ["coding-agent"],
        "advantages": [
            "Unified router for AI coding tools",
            "Multi-key rotation avoids rate limits",
            "Per-session cost tracking",
            "Desktop UI for easy switching",
            "OpenAI-compatible upstream",
        ],
        "businessAdvantages": [
            "Reduces rate-limit interruptions",
            "Cost visibility per coding session",
            "MIT license",
            "Lightweight — desktop app only",
        ],
        "apiIntegrationDetails": "Local proxy on http://localhost:8787 (default). Point coding tools to this URL with any API key — CC Switch routes upstream.",
    },
    {
        "name": "llm-browser",
        "displayName": "LLM Browser",
        "tagline": "Enable your AI agents to access any website without worrying about captchas, proxies, and anti-bot challenges.",
        "icon": "Globe",
        "color": "#0891b2",
        "category": "orchestration",
        "kind": "framework",
        "popularity": "low",
        "bestFor": [
            "AI agents that need reliable web access",
            "Bypassing captchas and anti-bot at scale",
            "Managed proxy rotation for scraping",
            "Replacing brittle custom scraping infra",
        ],
        "capabilities": [
            "Headless browser-as-a-service with anti-bot evasion",
            "Rotating residential proxies",
            "LLM-friendly API: 'fetch this page as readable text'",
            "Captcha solving integrated",
            "Return clean markdown for LLM consumption",
        ],
        "whenToUse": [
            "Your agents keep getting blocked by captchas",
            "You need residential IPs for geo-distributed scraping",
            "You want clean markdown from any page",
        ],
        "limitations": [
            "Paid service — costs per page fetched",
            "Adds latency vs direct fetch",
            "Best for moderate-volume agent browsing",
        ],
        "samplePrompts": [
            "Use LLM Browser to fetch a competitor's pricing page as markdown",
            "Have an agent scrape 50 product pages with LLM Browser",
            "Replace my Selenium scraper with LLM Browser",
        ],
        "setupNotes": "Sign up for an API key, then `curl https://api.llmbrowser.io/fetch -H \"Authorization: Bearer KEY\" -d '{\"url\":\"https://...\"}'`. Returns clean markdown.",
        "pricingTier": "Paid — from $29/mo for 5,000 pages",
        "docsUrl": "https://llmbrowser.io/docs",
        "availableModels": ["(provider-agnostic — feeds any LLM clean page content)"],
        "availableAgents": ["browser-agent", "scraper", "researcher"],
        "advantages": [
            "Captcha + anti-bot handled for you",
            "Residential proxy rotation",
            "Clean markdown output for LLMs",
            "Simple fetch API",
            "No browser infrastructure to manage",
        ],
        "businessAdvantages": [
            "Removes the biggest pain in agent web access",
            "No captcha-solving or proxy infra to maintain",
            "Per-page pricing — predictable cost",
            "Faster agent development for web tasks",
        ],
        "apiIntegrationDetails": "POST https://api.llmbrowser.io/fetch { url } with `Authorization: Bearer <key>` — returns `{ markdown, title, status }`.",
    },
]

# Build the TypeScript entries
def ts_arr(items, indent="    "):
    if not items:
        return "[]"
    parts = []
    for it in items:
        parts.append(f"{indent}`{it}`,")
    return "[\n" + "\n".join(parts) + "\n  ]"

def ts_entry(e):
    lines = []
    lines.append("  {")
    lines.append(f"    name: `{e['name']}`,")
    lines.append(f"    displayName: `{e['displayName']}`,")
    lines.append(f"    tagline: `{e['tagline']}`,")
    lines.append(f"    icon: `{e['icon']}`,")
    lines.append(f"    color: `{e['color']}`,")
    lines.append(f"    category: `{e['category']}`,")
    lines.append(f"    kind: `{e['kind']}`,")
    lines.append(f"    popularity: `{e['popularity']}`,")
    lines.append(f"    bestFor: {ts_arr(e['bestFor'])},")
    lines.append(f"    capabilities: {ts_arr(e['capabilities'])},")
    lines.append(f"    whenToUse: {ts_arr(e['whenToUse'])},")
    lines.append(f"    limitations: {ts_arr(e['limitations'])},")
    lines.append(f"    samplePrompts: {ts_arr(e['samplePrompts'])},")
    lines.append(f"    setupNotes: `{e['setupNotes']}`,")
    lines.append(f"    pricingTier: `{e['pricingTier']}`,")
    lines.append(f"    docsUrl: `{e['docsUrl']}`,")
    lines.append(f"    availableModels: {ts_arr(e['availableModels'])},")
    lines.append(f"    availableAgents: {ts_arr(e['availableAgents'])},")
    lines.append(f"    advantages: {ts_arr(e['advantages'])},")
    lines.append(f"    businessAdvantages: {ts_arr(e['businessAdvantages'])},")
    lines.append(f"    apiIntegrationDetails: `{e['apiIntegrationDetails']}`,")
    lines.append("  },")
    return "\n".join(lines)

block = "\n".join(ts_entry(e) for e in NEW_ENTRIES)

header = (
    "  // ─────────────────────────────────────────────────────────────\n"
    "  // Infrabase.ai alternatives — local inference engines, agent\n"
    "  // frameworks, and orchestration stacks referenced from\n"
    "  // https://infrabase.ai/alternatives/ollama\n"
    "  // ─────────────────────────────────────────────────────────────\n"
)

# Find the closing `];` of the PROVIDER_BENEFITS array and insert before it.
# The array ends with `  },\n];\n\n/** Quick lookup by provider name. */`
marker = "  },\n];\n\n/** Quick lookup by provider name. */"
if marker not in content:
    raise SystemExit("Marker not found in file")

# Insert block before the closing `];` (i.e., after the last entry's `},`)
replacement = "  },\n" + header + block + "\n];\n\n/** Quick lookup by provider name. */"
new_content = content.replace(marker, replacement, 1)
PATH.write_text(new_content)

print(f"Added {len(NEW_ENTRIES)} new entries to {PATH}")
print(f"New file size: {len(new_content)} bytes")
